Added Johnson-Cook Plasticity Model
hugary1995/raccoon pull request #132
Opened 2022-09-08 13:58 UTC by TheGreatCid

Added JC plasticity model for use in a variational framework. 
Additionally, return mapping is now floored at zero to avoid negative plastic strains.

Need a fix to JC documentation regarding having both a super and subscript on a single variable. 

Fixes issue #130

2022-09-08 14:17 UTC, hugary1995 requested changes
Thanks. I'll take a closer look when tests pass.

2022-09-08 14:17 UTC, hugary1995 commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  _trial[_qp] = stress_dev_norm;
Is this _trial used anywhere?

2022-09-08 14:17 UTC, hugary1995 commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  }
The code style here is to remove the enclosing braces if the subroutine is a one-liner.

2022-09-08 14:17 UTC, hugary1995 commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  }
I wonder if this ever happens as you've set the minimum permissible value to 0. I think either this check is redundant, or the minimum permissible value isn't doing its job. But if you want to be extra sure you can add an assert here, something like
```cpp
mooseAssert(_ep[_qp] >= 0 && delta_ep >= 0, "Error message otherwise");
```

2022-09-08 14:19 UTC, hugary1995 commented
The precheck is failing because your commit messages don't contain a ticket number. Just add "close #130" to any commit message.

2022-09-08 15:05 UTC, TheGreatCid commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  _trial[_qp] = stress_dev_norm;
Ah no. It was a debugging parameter that I forgot to remove.

2022-09-09 14:25 UTC, hugary1995 commented
A regression test is diffing.

2022-09-09 15:52 UTC, TheGreatCid commented
Interesting. I'll look into that

2022-09-09 17:07 UTC, TheGreatCid commented
Fixed the issue. 
I introduced a new material property for heat that was clashing with what already existed. 
I removed that, and now everything is working properly.

2022-09-09 17:35 UTC, hugary1995 commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  }
> Issues arrive at ep=0 for the log term in the plastic dissipation of the JC model. Nothing to do with the return mapping. Since `_heat[qp]` is normally called regardless of the existence of plastic strain, it is necessary to add a conditional to avoid the log(0) issue. Let me know if there is a more elegant solution I am not seeing.

Well, then you should guard against zero ep and delta_ep in `JohnsonCookHardening::plasticDissipation`, not here.

2022-09-09 17:35 UTC, hugary1995 commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  }
This is my last complaint. PR looks good otherwise.

2022-09-09 18:05 UTC, TheGreatCid commented on src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
> +  }
Good point. I'll add that in

2022-09-09 18:18 UTC, TheGreatCid commented
You were right, I did not need that floor protection to begin with

2022-09-12 15:07 UTC, merged