update fuction/property names after moose update
hugary1995/raccoon pull request #152
Opened 2023-07-13 21:01 UTC by BoZeng1997

update some object parameter names, function names so that they stop throwing warnings. Changes includes:

The RankTwoTensor initializer in PhaseFieldJIntegral
The "f_name" to "property_name" in CrackGeometricFunction and DegradationFunctionBase

2023-08-16 00:22 UTC, BoZeng1997 commented
more update based on moose 01a4027
1. add namespace std to pow function in Nucleation model objects
2. update getValue() function type to const

2023-08-25 21:36 UTC, BoZeng1997 commented
for MOOSE 7a54ed3 (Thu Aug 24 14:28:21), the update on const virtual function getValue() will hit compile error on dbg mode

2023-09-07 13:31 UTC, hugary1995 requested changes

2023-09-07 13:31 UTC, hugary1995 commented on include/bcs/DashpotPiecewiseBC.h
> + * Uses the term produced from integrating the diffusion operator by parts.
This explanation doesn't make sense to me. How is this related to the diffusion operator?

2023-09-07 13:31 UTC, hugary1995 commented on include/bcs/DashpotPiecewiseBC.h
> +   */
```suggestion
```

2023-09-07 13:31 UTC, hugary1995 commented on include/bcs/DashpotPiecewiseBC.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
The license header should use the RACCOON one.

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +    // _coefficient(getParam<Real>("coefficient")),
```suggestion
```

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +  // params.addParam<Real>("coefficient", 1.0, "The viscosity coefficient");
```suggestion
```

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +  InputParameters params = IntegratedBC::validParams();
params.addClassDescription(...)

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +  params.addCoupledVar("disp_z", "Displacement in the z direction");
Why not params.addCoupledVar("displacements", ...)?

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +      "coeff_compression", 1.0, "The viscosity coefficient when spring is in compression");
We don't say a dashpot is in tension/compression.

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +}
Where is `component`?

2023-09-07 13:31 UTC, hugary1995 commented on src/bcs/DashpotPiecewiseBC.C
> +}
This doesn't look right.

2023-09-07 15:47 UTC, BoZeng1997 commented
I am so sorry. The DashpotPiecewiseBC should have not been committed in the first place. I just removed related files. But thanks for the advice.

2023-09-07 16:19 UTC, hugary1995 commented
Please base against devel, not master.

2023-09-08 15:34 UTC, closed without merging