request from RR main
hugary1995/raccoon pull request #78
Opened 2021-05-25 17:58 UTC by rrezakhani

pull request to add several material and kernel source files as well as a benchmark problem for pressurized fracture.

2021-07-18 00:16 UTC, hugary1995 commented
Hi Roozbeh, I can finally work on this now -- sorry for taking so long. If you can give me write access to this branch, I can directly work on it.

2021-07-27 11:24 UTC, hugary1995 commented
You can see why the tests are failing by clicking on "details". For example, the `Precheck` fails because some files contain trailing white spaces. I think if you enforce the .clang-format in the root directory they should be gone. Although I'm not sure how to set it up in spy. There is also one file containing banned keywords.

2021-07-27 14:05 UTC, rrezakhani commented
Thanks, I will work on it today.

************************************************************************
Roozbeh Rezakhani, PhD
Postdoctoral Researcher
Department of Mechanical Engineering and Material Science
Duke University
Durham, NC, USA
Email: ***@***.***
Cell: +1 224 204 4500
************************************************************************


On Tue, Jul 27, 2021 at 7:25 AM Gary (Tianchen) Hu ***@***.***>
wrote:

> You can see why the tests are failing by clicking on "details". For
> example, the Precheck fails because some files contain trailing white
> spaces. I think if you enforce the .clang-format in the root directory they
> should be gone. Although I'm not sure how to set it up in spy. There is
> also one file containing banned keywords.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hugary1995/raccoon/pull/78#issuecomment-887431867>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKK4RAOIH2XZP4UI3MZ2JCDTZ2JRFANCNFSM45P4RHMQ>
> .
>

2021-07-29 23:53 UTC, hugary1995 requested changes
Thanks Roozbeh, looks pretty good overall. I have done the first round review - mostly some formatting issues.

Most of the comments are notes to myself. But if you can go through them and stick to the formatting guideline in future PRs, that'll be really helpful.

2021-07-29 23:53 UTC, hugary1995 commented on .directory
> +[Dolphin]
I am not sure what these `.directory` files are. Are they generated by your editor/system? I will delete them, and also add them to `.gitignore`, so that you won't accidentally check them in in the future.

2021-07-29 23:53 UTC, hugary1995 commented on benchmarks/hydraulic_fracture/fracture.i
> +###############################################################################
I'll move this `hydraulic_fracture` folder into the tutorials folder if you are okay with that.

2021-07-29 23:53 UTC, hugary1995 commented on benchmarks/hydraulic_fracture/fracture.i
> +  picard_custom_pp = 'norm_d'
```suggestion
  fixed_point_max_its = 20
  disable_fixed_point_residual_norm_check = true
  fixed_point_custom_pp = 'norm_d'
```
Not sure if you noticed it, those "picard" parameters have been deprecated. Now they are termed "fixed_point". We should avoid using deprecated parameters in new files that we check in.

2021-07-29 23:53 UTC, hugary1995 commented on benchmarks/hydraulic_fracture/run.sh
> +mpiexec -n 12 ~/Projects/raccoon/raccoon-opt -i fracture.i
Let's not check in irrelevant files.

2021-07-29 23:53 UTC, hugary1995 commented on benchmarks/mode1_geometric_notch_fatigue/fracture.i
> +E = 2.1e5
I'll move this folder to the tutorials folder as well, if you are okay with that.

2021-07-29 23:53 UTC, hugary1995 commented on benchmarks/mode1_geometric_notch_fatigue/run.sh
> +mpiexec -n 12 ~/Projects/raccoon/raccoon-opt -i fracture.i
I'll delete this file.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADAnisotropicDiffusion.md
> +
Can you add the weak form associated with this kernel? You can either add it in the `addClassDescription`method in the source file, or just add a line here.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADMaterialDerivativeTestKernel.md
> +
Same here, just add a simple equation about the weak form.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADPoroMechanicsCoupling.md
> +
Weak form here.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADPorousFlowTimeDerivative.md
> +
Weak form here.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADSPFPressureTimeDerivative.md
> +
Weak form here.

2021-07-29 23:53 UTC, hugary1995 commented on doc/content/source/kernels/ADSPFVolStrTimeDerivative.md
> +
Weak form here. Well, the same goes to all `.md` files.

2021-07-29 23:53 UTC, hugary1995 commented on include/diracKernel/DiracSource.h
> +  Point _point;
For all of the members, we need to add doxygen style in-code documentations. For example, take a look at `LargeDeformationElasticityModel.h`.

There are various ways of writing an in-code documentation. For most of these simple members, just a one liner would be sufficient, e.g.
```cpp
    /// The point where the source is applied
    Point _point;
```

2021-07-29 23:53 UTC, hugary1995 commented on include/diracKernel/DiracSource.h
> +  int _dim;
```suggestion
  /// Dimension of the mesh
  int _dim;
```
Also a one liner comment here (and for all the rest of the members).

2021-07-29 23:53 UTC, hugary1995 commented on include/diracKernel/DiracSource.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
This license heading needs to be changed.

2021-07-29 23:53 UTC, hugary1995 commented on include/diracKernel/DiracSource.h
> +class DiracSource;
I don't think forward declaration is needed here.

2021-07-29 23:53 UTC, hugary1995 commented on include/diracKernel/DiracSource.h
> +InputParameters validParams<DiracSource>();
This templated validParams is also not needed any more. Instead of a templated validParams, add a public static member below, i.e.
```cpp
public: 
  static InputParameters validParams();
```

2021-07-29 23:53 UTC, hugary1995 commented on include/ics/PhasefieldShapes.h
> +/****************************************************************/
This license heading needs to be changed.

2021-07-29 23:53 UTC, hugary1995 commented on include/ics/PhasefieldShapes.h
> +#define PHASEFIELDSHAPES_H
No more `ifndef` guards, use `#pragma once` instead.

2021-07-29 23:53 UTC, hugary1995 commented on include/ics/PhasefieldShapes.h
> +InputParameters validParams<PhasefieldShapes>();
Same comment goes to all your header files:
- No forward declarations (at least for most of the classes themselves) are needed any more.
- No more templated validParams. Use a public static member instead.

2021-07-29 23:53 UTC, hugary1995 commented on include/ics/PhasefieldShapes.h
> +  std::vector<Real> _gradient_values;
Add comments to all of them.

2021-07-29 23:53 UTC, hugary1995 commented on include/ics/PhasefieldShapes.h
> +#endif //PHASEFIELDSHAPES_H
No more `ifndef` guards.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADMaterialDerivativeTestKernel.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADPorousFlowTimeDerivative.h
> +  const ADVariableValue & _S_dot;
This seems like an unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADSPFPressureTimeDerivative.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADSPFPressureTimeDerivative.h
> +>>>>>>> 9a9eb03838cb5bb4b15db64daa1ab4ce7b38a242
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADSPFVolStrTimeDerivative.h
> +>>>>>>> 9a9eb03838cb5bb4b15db64daa1ab4ce7b38a242
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADValueKernelCoupled.h
> +/****************************************************************/
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADValueKernelCoupled.h
> +
ifndef guards.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ADValueKernelCoupled.h
> +  const Real & _coeff;
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ValueKernel.h
> +/****************************************************************/
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ValueKernelCoupled.h
> +/****************************************************************/
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ValueKernelCoupled.h
> +#define ValueKernelCoupled_H
ifndef guards.

2021-07-29 23:53 UTC, hugary1995 commented on include/kernels/ValueKernelCoupled.h
> +  const Real & _coeff;
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/ADComputeFluidMobility.h
> +<<<<<<< HEAD
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/ADComputeFluidMobility.h
> +  const Real & _mob_eps;
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/ADComputePorosity.h
> +  const ADMaterialProperty<Real> & _M;
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/ComputePorosity.h
> +  const MaterialProperty<Real> & _M;
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/DegradationBase.h
> +//* This file is part of the RACCOON application
No, this file has been deleted I believe. Why do you want to bring it back?

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/FatigueMobility.h
> +<<<<<<< HEAD
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on include/materials/FatigueMobility.h
> +};
Comments.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +  //params.addParam<MaterialPropertyName>("density_name","density", "name of the density material");
Remove unused comment.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +#define _USE_MATH_DEFINES
I'm not sure if this macro is needed.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +  //Real _pressure_source = _p0;
Remove unused comments.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +<<<<<<< HEAD
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +  Real _pressure_source = 1/_tP*4*M_PI/_rho*_upcoeff/_downcoeff*_p0*_d1*(std::max((1+tanh((_shot_t-_t1)/_tRT))*std::exp(-(_shot_t-_t1)/_tL)*cos(2*M_PI*_fL*(_shot_t-_t1)+M_PI/3),0.0));
This is really hard to read. If you configure your editor to use clang-format, it will automatically format the code for you.

2021-07-29 23:53 UTC, hugary1995 commented on src/diracKernel/DiracSource.C
> +    _dim(getParam<int>("dim")),
Is this the mesh dimension? If so, we can directly get this information from the mesh, without asking it from the user.

2021-07-29 23:53 UTC, hugary1995 commented on src/ics/PhasefieldShapes.C
> +/****************************************************************/
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on src/ics/PhasefieldShapes.C
> +{
The indentation here is also weird. This shouldn't happen if clang-format is being enforced.

2021-07-29 23:53 UTC, hugary1995 commented on src/kernels/ADAnisotropicDiffusion.C
> +<<<<<<< HEAD
Unresolved conflict.

2021-07-29 23:53 UTC, hugary1995 commented on src/kernels/ADMaterialDerivativeTestKernel.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on src/kernels/ADSPFPressureTimeDerivative.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on src/kernels/ADValueKernelCoupled.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-29 23:53 UTC, hugary1995 commented on src/kernels/ValueKernelCoupled.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fix license.

2021-07-30 17:37 UTC, hugary1995 requested changes
Some more questions...

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ADAnisotropicDiffusion.md
> +
I wonder if a kernel with the same functionality is already available.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ADMaterialDerivativeTestKernel.md
> +
I have questions about the naming here.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ADValueKernelCoupled.md
> +
Weak form.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ADValueKernelCoupled.md
> +
I also wonder if there is an existing kernel of the same functionality.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ValueKernel.md
> +
Weak form.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/kernels/ValueKernel.md
> +
I think there is already a kernel with the same functionality.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/materials/ADComputeFluidMobility.md
> +
Please write some equations here on how the mobility is calculated.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/materials/ADComputePorosity.md
> +
Some equations here as well.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/materials/ComputePorosity.md
> +
We've decided to go AD all the way in RACCOON. We don't need any non-AD classes.

2021-07-30 17:37 UTC, hugary1995 commented on doc/content/source/materials/FatigueMobility.md
> +
Some equations here as well.

2021-09-20 07:38 UTC, hugary1995 commented
Hi @rrezakhani, could you please remind me where we were on this? Are you just waiting for my changes? If so, let me know and I'll work on this. I would like to get this PR in soon so that I can start preparing that SoftwareX paper.

2021-11-09 10:07 UTC, hugary1995 commented
> Gary, I removed those unnecessary source files and tried to push, but it says there are things that have been done on github: To github.com:rrezakhani/raccoon.git ! [rejected] RRmain -> RRmain (fetch first) error: failed to push some refs to '[git@github.com](mailto:git@github.com):rrezakhani/raccoon.git' hint: Updates were rejected because the remote contains work that you do hint: not have locally. This is usually caused by another repository pushing hint: to the same ref. You may want to first integrate the remote changes hint: (e.g., 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> 
> Have you done some modifications?

Yes, I have made several modifications. Can you do a `git fetch` then rebase your work on top of the remote head?

2021-11-09 10:07 UTC, hugary1995 commented
Sorry for the late reply -- I was taking vacation for the last two weeks.

2021-11-09 10:10 UTC, hugary1995 commented
I suspect that you may encounter several conflicts when trying to do the rebase. If you want we can meet via zoom and look at it together.

2024-10-09 15:51 UTC, TheGreatCid commented
This has gone stale. Closing.

2024-10-09 15:51 UTC, closed without merging