Added Spectral and VolDev Split to Hencky Model
hugary1995/raccoon pull request #81
Opened 2021-06-22 17:08 UTC by TheGreatCid

2021-06-25 21:45 UTC, hugary1995 commented
Sorry I've been kept with some other things. I swear I'll look at this next week.

2021-07-07 13:40 UTC, TheGreatCid commented
Have you had a chance to look at this?
I am not sure why checks are failing

2021-07-07 15:42 UTC, hugary1995 commented
I was working on #79 to get tests to pass. After #79 is merged, you can rebase this branch and I will merge it.

You can see why the tests are failing by clicking on details. In your case the Pretest failed because the PR doesn't reference a valid issue.

2021-07-18 00:07 UTC, hugary1995 commented
Sorry for taking so long. I just merged the fix to the testing system. Could you now rebase your branch? I'll review it in the meantime. Thanks!

2021-07-18 00:14 UTC, hugary1995 requested changes
Overall looks very good. Thanks for your contribution!

It would be nice if you can add this two new formulations in the HenckyIsotropicElasticity.md documentation as well.

2021-07-18 00:14 UTC, hugary1995 commented on src/materials/large_deformation_models/HenckyIsotropicElasticity.C
> +  // be some plastic flow. The foolowing operations cancel out with an exponentiation of Fe, so we
```suggestion
  // be some plastic flow. The following operations cancel out with an exponentiation of Fe, so we
```

2021-07-18 00:14 UTC, hugary1995 commented on src/materials/large_deformation_models/HenckyIsotropicElasticity.C
> +  // only do this in the case of exponentiate == false
```suggestion
  // only do this in the case of plasticity_update == false
```
I know you probably just copied it from some other place written by me. I think I said it wrong there as well.

2021-07-18 00:14 UTC, hugary1995 commented on src/materials/large_deformation_models/HenckyIsotropicElasticity.C
> +  // only do this in the case of exponentiate == false
```suggestion
  // only do this in the case of plasticity_update == false
```

2021-07-18 15:19 UTC, TheGreatCid commented
I'll update the documentation tomorrow! I'll let you know when that is ready

2021-07-18 16:50 UTC, hugary1995 commented
The precheck fails because none of the commit messages contains an issue number. Try to amend your last commit and force push.

2021-07-19 02:56 UTC, TheGreatCid commented
Don't merge this quite yet. Still need to update documentation. I just wanted to make sure I could fix my last commit

2021-07-19 14:30 UTC, hugary1995 approved these changes

2021-07-19 14:30 UTC, merged