Jint surfing
hugary1995/raccoon pull request #88
Opened 2021-07-19 18:58 UTC by BoZeng1997

A negative J2 invariant should never happen again. But I have not yet found out why the J integral over the boundary does not approach the value of the prescribed Gc.
In the folder /benchmark/AT2surfing, there are input deck for surfing boundary problem under AT-2 without irreversibility. As a standard phase-field fracture problem it still cannot return a close value to Gc.

2021-07-19 19:07 UTC, hugary1995 requested changes
Please remove the scripts for submitting jobs. Also remove output files like `surf_AT2_Gc2L0.35del1.16_dt1e-2_J5b_14523984`.

2021-07-19 19:07 UTC, hugary1995 commented on benchmarks/AT2surfing/submit.sh
> +#!/bin/bash
Remove this file from version control. You can use for example `git rm` for that.

2021-07-19 19:07 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +// }
Remove these comments.

2021-07-19 19:07 UTC, hugary1995 commented on tutorials/mode1_brittle_fracture/submit.sh
> +#!/bin/bash
Remove this file from version control.

2021-07-19 19:07 UTC, hugary1995 commented on tutorials/mode1_cohesive_fracture/submit.sh
> +#!/bin/bash
Remove this file from version control.

2021-07-19 19:08 UTC, hugary1995 commented
Directly writing to standard streams (like std::cout) is prohibited. You can use them in your local branching for debugging purposes, but remember to remove those in a PR.

2021-07-19 19:20 UTC, hugary1995 requested changes
Overall looks good. I suggest we start from cleaning up some unused comments. Then we can double check the implementation.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  # []
Remove unused comments in the input files.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  # []
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  # []
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +# []
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +# []
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  # []
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +#include "ADMaterial.h"
```suggestion
#include "Material.h"
```

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +class GeneralizedExternalDrivingForce : public ADMaterial
```suggestion
class GeneralizedExternalDrivingForce : public Material
```

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const MaterialPropertyName _ex_driving_name;
Add a doxygen string for each of the parameter here. For example, say
```
/// Name of the external driving energy
const MaterialPropertyName _ex_driving_name;
```

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  ADMaterialProperty<Real> & _ex_driving;
Add a doxygen string.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  // const Real & _Gc;
It should be a `const ADMaterialProperty<Real> &`

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const Real & _L;
This should be a `const ADMaterialProperty<Real> &`.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const Real & _mu;
Same here, they should be `const ADMaterialProperty<Real> &`

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  ///
Missing comment.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  ///
Missing comments.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  // const ADMaterialProperty<Real> & _invar_2;
Remove unused comments.

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const MaterialPropertyName _rank_two_tensor;
What's this `_rank_two_tensor`?

2021-07-19 19:20 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +// const GenericMaterialProperty<RankTwoTensor, is_ad> & _stress;
Remove unused comment.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +// #include "ADRankTwoTensorForward.h"
Remove unused comments.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +//      "The displacements appropriate for the simulation geometry and coordinate system");
Remove unused comments.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +                             "Ce()");
The line wrap here is weird, they should be in the same line.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "energy_release_rate", "energy release rate or fracture toughness");
```suggestion
  params.addParam<Real>(
      "energy_release_rate", "Gc", "energy release rate or fracture toughness");
```

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "phase_field_regularization_length", "phase_field_regularization length");
```suggestion
  params.addParam<Real>(
      "phase_field_regularization_length", "l", "The phase field regularization length");
```
Use a descriptive description here.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "Lame_first_parameter", "Lame's first parameter Lambda");
```suggestion
  params.addRequiredParam<Real>(
      "lambda", "Lame's first parameter Lambda");
```

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "delta", "delta");
The line wraps are weird. Are you using clang-format?

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  // params.addRequiredParam<ADMaterialProperty<Real>>("second_invariant","The second standard invariants of stress tensor");
Remove these comments.

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "rank_two_tensor","name of the stress tensor");
No need for this. I think the stress tensor is always called "stress".

2021-07-19 19:20 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +//    _disp(3)
Remove unused comments please.

2021-07-19 19:48 UTC, BoZeng1997 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  // const Real & _Gc;
I am not computing based on qp. For now it can stay just a Real

2021-07-19 19:53 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "delta", "delta");
this is the only way i can see all of them in half of the screen.

2021-07-19 20:22 UTC, BoZeng1997 commented
I have cleaned unused comments and complete the necessary comments. But I did not make changes that will cause further changing in input deck. Were they changed, all of the input deck must be changed. I cannot guarantee a same result.

The problem right now is not with kumar's model, but j integral in general.

In the folder /benchmark/AT2surfing, there is input deck for surfing boundary problem under AT-2 without irreversibility (with irreversibility commented). The problem right now is that in the AT-2 model, with smaller mesh size, it still cannot return a close value to Gc.

2021-07-19 20:25 UTC, BoZeng1997 commented
... the number of changes made is still very large. I think it is because i rm your examples. I thought that is a way not to track the change in it.

2021-07-19 20:28 UTC, hugary1995 commented
The number of lines of addition is huge because you've checked in many exodus files -- remove those.
The number of lines of deletion is huge because you've removed everything in the benchmarks folder. We do plan to remove the entire benchmarks folder at some point in the future, but don't do that for now.

2021-07-19 20:53 UTC, BoZeng1997 commented
recovered benchmark examples.
cleared other redundancy.

2021-07-19 21:11 UTC, hugary1995 commented
Fantastic, thanks.

2021-07-19 22:13 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "delta", "delta");
That's an issue with your editor. You should be able to configure the maximum column width within your editor. But the source code has to be clang-formated.

2021-07-19 22:29 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "delta", "delta");
ok i will figure that out

2021-07-19 22:37 UTC, hugary1995 requested changes
We are getting close. I think I found the cause of your J-R curve issue.

Also, please enforce clang-format -- most long equations are pretty unreadable right now. If you need help setting up clang-format just let me know.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +    output_properties = 'psie_active' #elastic_strain
`psie_active` is not the elastic strain.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  []
Why do we need this converter?

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  file_base = surf_AT2_Gc2L0.35del1.16_dt1e-2_J5b_noirr_ela
I know you are probably doing a parameter study on your own branch. But let's choose a simpler file name for here.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  append_date = true
Do not append date.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  []
Why using a constant lower bound here?

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  []
ce isn't used anywhere.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  file_base = surf_AT2_Gc2L0.35del1.16_dt1e-2_J5b_noirr_frac
Do not generate output from the subapp.

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  append_date = true
Do not append date, as that will make it impossible to do regression tests.

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const Real & _Gc;
I know you were probably using a `const Real &` for your own testing purposes. But it should be a `const ADMaterialProperty<Real> &` in the master branch to be consistent with all other objects.

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  const Real & _mu;
Same thing here. They should be `const ADMaterialProperty<Real> &`

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  Real _gamma_2;
values computed during ______?

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  /// tje degraded stress tensor
```suggestion
  /// The stress
```

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  Real _gamma_2;
I don't think they need to be defined as members. They are quantities you compute at every qp, and you don't need to store them as material properties, because they won't be used by anything else, and they won't be output for visualization.

2021-07-19 22:37 UTC, hugary1995 commented on include/materials/GeneralizedExternalDrivingForce.h
> +  ADMaterialProperty<Real> & _J2;
Same comment here: I don't think they should be declared as members and stored as material properties.

2021-07-19 22:37 UTC, hugary1995 commented on include/postprocessors/PhaseFieldJIntegral.h
> +#include "RankTwoTensor.h"
```suggestion
#include "RankTwoTensorForward.h"
```

2021-07-19 22:37 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +    elastic_energy_name = psie_active
Most likely, the error in your J-R curve comes from here. Here you need to pass in the strain energy density, i.e. `g * psie_active + psie_inactive`, instead of just the active strain energy density.

2021-07-19 22:37 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +    ,_J2(declareADProperty<Real>("J2"))
Please enforce clang-format, commas cannot be the first character of a line. Let me know if you need help setting up clang-format.

2021-07-19 22:37 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  _gamma_2 = (1.0+_delta)*(_sigma_cs+_sigma_ts)/(2.0*_sigma_ts*_sigma_cs)*std::sqrt(3.0);
They should be computed at each qp, because `lambda` and `mu` can be inhomogeneous.

2021-07-19 22:37 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  }
```suggestion
  mooseAssert(_J2[_qp] >= 0, "Some messages here if the assertion fails");
```
But I don't think you need this assertion anyways, it's always gonna be nonnegative.

Also, this is not the usual way of computing J2. J2 is simply the norm of the deviatoric part of the stress.

2021-07-19 22:37 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  _beta_3[_qp] = (1-std::sqrt(I1*I1)/I1)*(_J2[_qp]/2.0/_mu+I1*I1/6.0/(3.0*_Lambda+2.0*_mu));
Again, these `beta`s don't need to be material properties. Just declare them as `Real` within this scope.

2021-07-19 22:41 UTC, hugary1995 commented
Here is a decision for you to make: if you only want to demonstrate the usage of J-integral in this PR, then all you need are the source code for the J-integral postprocessor and one tutorial input file. If you also want to check in the Kumar model, then in addition to the source code that you have checked in, I also need to see at least regression test/tutorial the demonstrate its usage.

I'm fine with both, it's up to you.

2021-07-19 22:45 UTC, hugary1995 commented
You can see why the tests are failing if you click on `details`. For example, the `Precheck` is currently because:
```
##########################################################################
ERROR: Your patch does not contain a valid ticket reference! (i.e. #1234)
Merge branch 'JintSurfing' of https://github.com/BoZeng1997/raccoon into test
clear
recover examples
Jintsurfing-clean2
AT2surfing-clean
for AT2 Jintegral Surfing only
GeneralizedKumar_issue_Jint
all kinds of kumar for test
lastindirectkumar
modifyGeneralizedExternalDrivingForce to have ce in elasticity.i
recover tutorials from upstream
recover tutorials
20210623_updateKumar_ProblemNAN
first_extdriving

ERROR: The following files contain banned keywords (std::cout, std::cerr, sleep, print_trace):
	src/materials/GeneralizedExternalDrivingForce.C
##########################################################################
```

2021-07-20 12:44 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +    output_properties = 'psie_active' #elastic_strain
I did not mean `psie_active` is `elastic_strain`. i commented `elastic_strain` to not output it.

2021-07-20 12:44 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +  []
because J integral object requires pk1_stress

2021-07-20 12:45 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +  file_base = surf_AT2_Gc2L0.35del1.16_dt1e-2_J5b_noirr_ela
got it

2021-07-20 12:47 UTC, BoZeng1997 commented on benchmarks/AT2surfing/fracture.i
> +  []
In kumar's paper, they release the restriction on irreversibility until d = 0.95. I did not how to do that exactly in raccoon, so I first tried with no irreversibility at all since last Thursday.

2021-07-20 12:55 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  []
The right thing to do here is to add an optional parameter in the `PhaseFieldJIntegral` postprocessor that asks for the name of the stress tensor, something like:
`params.addParam<MaterialPropertyName>("stress", "stress", "Name of the stress tensor");`

2021-07-20 12:57 UTC, hugary1995 commented on benchmarks/AT2surfing/fracture.i
> +  []
I see. I would prefer to use the constraint in its "correct" form. Then if we see issues with that, we fix it (instead of using someone's "engineering" approach).

2021-07-20 13:14 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  _beta_3[_qp] = (1-std::sqrt(I1*I1)/I1)*(_J2[_qp]/2.0/_mu+I1*I1/6.0/(3.0*_Lambda+2.0*_mu));
They were the product of once me trying to fix the negative J2 problem. i will remove them.

2021-07-20 13:58 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  }
How to compute J2? like:
RankTwoTensor stress_deviatoric = stress.deviatoric();
J2 = stress_deviatoric.doubleContraction(stress_deviatoric)/2;

2021-07-20 14:03 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +    elastic_energy_name = psie_active
So in my case, since i am not using decomposition, it should be `psie = g * psie_active`

2021-07-20 14:04 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  }
Will this assert catches an imaginary part?

2021-07-20 14:13 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +    elastic_energy_name = psie_active
Two material properties are output from the constitutive model: `psie` and `psie_active`, where `psie = g * psie_active + psie_inactive`. So in your case, you can just use `psie`.

2021-07-20 14:15 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  }
You can use
```
ADRankTwoTensor stress_dev = stress.deviatoric();
ADReal J2 = stress_dev.doubleContraction(stress_dev);
```
You can derive it yourself, i.e. expand the double contraction and see if it is the same expression as your original code.

2021-07-20 14:17 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  }
> Will this assert catches an imaginary part?

`Real` doesn't contain an imaginary part. Also a norm can never be imaginary.

2021-07-20 14:48 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +    elastic_energy_name = psie_active
with psie, J2 = 9.6e-2, 5% error from Gc = 9.1e-2. the error is smaller, but is it small enough?

2021-07-20 15:17 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +    elastic_energy_name = psie_active
I think it's fairly small, but it doesn't really make sense to compare just one number, we need to look at the JR curve as a function of crack extension.

2021-07-20 15:54 UTC, BoZeng1997 commented
what issue should it be linked to? Tutorial?

2021-07-20 16:02 UTC, BoZeng1997 commented
what is this ticket reference exactly? is not mine #88 ?

2021-07-20 16:06 UTC, BoZeng1997 commented
COPY FROM MOOSE WEBPAGE:

Referencing Issues
Every modification to MOOSE must reference an issue number. This means that every Pull Request (PR) that flows into MOOSE must have contain at least one commit that references an issue relevant to what you are working on (e.g. refs #<number> (where <number> is an issue number on the MOOSE GitHub issue page, such as #1234). If your PR completely addresses an issue, you can automatically close it by prepending "closes" or "fixes" to the issue reference (e.g., closes #1234). Issue numbers are automatically checked by our testing system.

2021-07-20 16:09 UTC, hugary1995 commented
If you don't find a relevant issue, you can create your own. Then you can modify your commit message to reference that issue.

2021-07-20 16:17 UTC, BoZeng1997 commented
> Here is a decision for you to make: if you only want to demonstrate the usage of J-integral in this PR, then all you need are the source code for the J-integral postprocessor and one tutorial input file. If you also want to check in the Kumar model, then in addition to the source code that you have checked in, I also need to see at least one regression test/tutorial that demonstrates its usage.
> 
> I'm fine with both, it's up to you.

For example, is the input deck already committed in this folder enough to be a tutorial input file for simply J integral? 

I do also want to check the kumar model, since I have already committed the object and it cannot return a Jintegral value close to that of AT2. I want to know what kind of test is good enough as a regression test. can surfing boundary value problem serve as a regression test? we know the expected speed of the crack propagation but the result need to be obtained from paraview.

2021-07-20 17:04 UTC, hugary1995 commented
> For example, is the input deck already committed in this folder enough to be a tutorial input file for simply J integral?

Yes.

> I do also want to check the kumar model, since I have already committed the object and it cannot return a Jintegral value close to that of AT2. I want to know what kind of test is good enough as a regression test. can surfing boundary value problem serve as a regression test? we know the expected speed of the crack propagation but the result need to be obtained from paraview.

You might have misunderstood the meaning of regression test. Regression test is used to ensure consistency, not for correctness.

Take a look at other files in the tutorials folder, each tutorial has its own `tests` specification. Most of them are simply diffing the output against some `gold` files you check in. This is to make sure future changes to raccoon do not break you stuff.

2021-07-20 17:19 UTC, BoZeng1997 commented
> > For example, is the input deck already committed in this folder enough to be a tutorial input file for simply J integral?
> 
> Yes.
> 
> > I do also want to check the kumar model, since I have already committed the object and it cannot return a Jintegral value close to that of AT2. I want to know what kind of test is good enough as a regression test. can surfing boundary value problem serve as a regression test? we know the expected speed of the crack propagation but the result need to be obtained from paraview.
> 
> You might have misunderstood the meaning of regression test. Regression test is used to ensure consistency, not for correctness.
> 
> Take a look at other files in the tutorials folder, each tutorial has its own `tests` specification. Most of them are simply diffing the output against some `gold` files you check in. This is to make sure future changes to raccoon do not break you stuff.

I did misunderstand the regression test.

But for now, since we are not updating our moose, is one tutorial file, say kumar's model with surfing BVP,  enough for kumar's usage?

2021-07-20 17:38 UTC, hugary1995 commented
Yes, that's sufficient. It will demonstrate the usage of both the J integral post processor and the nucleation model.

2021-07-20 20:47 UTC, hugary1995 commented
Just ping me when you think this PR is ready for review.

2021-07-20 20:50 UTC, hugary1995 requested changes
Caught a few more minor things.

2021-07-20 20:50 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +[]
This is not quite right. The surfing BC should be applied to all of the external boundaries (excluding crack surfaces), and should be applied to both `disp_x` and `disp_y`.

2021-07-20 20:50 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  []
Reaction force isn't needed in this example.

2021-07-20 20:50 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +[]
Add a postprocessor to integrate the crack surface density.

2021-07-20 20:50 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +    save_in = fy
reaction force isn't needed in this example.

2021-07-20 20:50 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +  []
Reaction force isn't needed in this example.

2021-07-20 21:00 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +[]
Do you mean it should be also applied to the (outer) left, top, right, and bottom, and on two directions for each boundary?

2021-07-20 21:02 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +[]
it is in material

2021-07-20 21:03 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +[]
`[Materials]`

2021-07-20 21:08 UTC, BoZeng1997 commented on benchmarks/AT2surfing/elasticity.i
> +[]
In kumar's paper, they were only applying disp_y on top and bottom.

2021-07-20 22:00 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +[]
Yes, I can see that. I am saying you should integrate the crack surface density "gamma" which is computed in the material into a scalar representing the total crack surface area. Something like
```
[a]
  type = ADElementIntegralMaterialProperty
  mat_prop = gamma
[]
```

2021-07-20 22:01 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +[]
I guess you were integrating that in paraview, which isn't unreliable.

2021-07-20 22:02 UTC, hugary1995 commented on benchmarks/AT2surfing/elasticity.i
> +[]
That's something to discuss tomorrow for sure.

2021-07-20 23:06 UTC, BoZeng1997 commented
It is ready for review now. I have made modifications to most of the issues mentioned above. I still keep the J2 and F_surface in the object GeneralizedExternalForce because it will be useful for debuging. They will not be stored in the future. The surfing boundary condition did not change.

2021-07-20 23:08 UTC, BoZeng1997 commented
I am not sure it will pass the checks. I need to run for the bus now

2021-07-21 00:38 UTC, hugary1995 commented
Thanks, this is getting really close now. The "Travis CI" test fails because of documentation failure -- some classes are missing documentations.

Let's discuss about the boundary condition in tomorrow's group meeting.

A few minor things:
- Now that you've added that `benchmarks/surfingBVP` example, the `benchmarks/AT2surfing` example becomes redundant, so lets remove that one.
- We shouldn't be adding any new examples into that `benchmarks` folder -- those are our old examples. We want to migrate everything to the new `tutorials` folder. So could you move your `benchmakrs/surfingBVP` example into the tutorials folder? I think that will be a very useful tutorial for everyone. Also, let's try to keep it consistent with the naming convention in that folder, so instead of `surfingBVP`, let's rename it to something like `surfing_BVP` with an underscore.
- One last thing you need to do is to tell the testing system how this new tutorial should be tested. To do that, you need to add a file called `tests` in the folder of your example. In that `tests` file, you should describe how the test should run. You can simply copy from another `tests` from an existing tutorial. Make sure you only run it for one or two steps so that the test can finish within 20 seconds.
- One other thing you could do, although not necessary, is to document the tutorial. To document a tutorial, first add an entry to the menu in `doc/menu.yml`, something like `12. Steady crack propagation: tutorials/12_surfing.md`. Then add the actual documentation page at `doc/content/tutorials/12_surfing.md`. You can copy from existing documentations, e.g. `01_small_deformation_elasticity.md`, as a starting point.

As a reminder, to build documentation on your own machine:
- commit everything, make sure everything is tracked by git
- compile your application, make sure it is up-to-date
- `cd doc`
- `./moosedocs.py build --serve`, this will build the documentation and serve the website at your localhost.

2021-07-30 01:15 UTC, hugary1995 commented
Hey Bo, have you had a chance to address those comments? If you need help with anything just let me know.

2021-07-30 01:43 UTC, BoZeng1997 commented
I was not on it this week. My Mac machine became slow again and I have to focus on one task. It is slow even just typing on Github page. My laptop is back and I am preparing it back to work. I will be back on this soon.

2021-07-30 02:00 UTC, hugary1995 commented
Okay no worries -- wasn't pushing you.

2021-07-30 21:48 UTC, BoZeng1997 commented
Do you accept a kumar's  that might be wrongly implemented? I am still looking for the reason I cannot have Jintegral = Gc.

2021-07-30 23:24 UTC, hugary1995 commented
It's not related to the nucleation model, is it? You've shown that J isn't exactly equal to Gc even with standard AT1 or AT2.

2021-07-30 23:44 UTC, hugary1995 commented
But I do remember that when I tried the surfing problem, I got J = Gc for a purely elastic case. Let me play with it and see if I can reproduce what I had before.

2021-08-02 17:23 UTC, BoZeng1997 commented
I think it may have to do with the difference in the 2020 formulation and the 2021 formulation. What I have pushed in is the 2021 version. The 2020 version gave a result Jint/Gc = 0.95 which is good. But the 2021 version has improved behavior on compression( said in paper). I need to decide which pair of formulation and example to push in. The ones you saw in github is the 2021 formulation with 2020 example (they probably do not match).

2021-08-11 15:57 UTC, BoZeng1997 commented
not for review yet

2021-08-31 13:44 UTC, BoZeng1997 commented
> I see why the `Test` test is failing for you. That's because you committed a new submodule moose. Please don't do that.

How do I remove this redundant moose safely?

2021-09-02 19:07 UTC, BoZeng1997 commented
> Yes, you should worry about those errors. These errors tell you exactly what files are missing. These errors will prevent the Documentation test from passing, and a PR cannot be merged with a failing test.
> 
> > The ./moosedocs.py build --serve process almost stuck at [I 210827 14:41:40 handlers:64] Start detecting changes . Is this normal?
> 
> It is not stuck, it is detecting changes. You should be able to view the documentation website locally at your localhost.

How long should this step usually take?

2021-09-02 19:43 UTC, BoZeng1997 commented
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   doc/menu.yml
        modified:   moose (new commits)
        modified:   tutorials/surfing_boundary_problem/test

no changes added to commit (use "git add" and/or "git commit -a")
```
I cannot restore the moose (new commit)

2021-09-03 19:48 UTC, BoZeng1997 commented
I install the most up-to-date clang format 11 on my Mac machine and tried clang-format the src code of GeneralizedExternalDrivingForce.C. The result is the same as the one which got rejected by this clang-format check in the first place. So it was not the problem of my clang-format version. There has to be some setting in clang format that should not be default value. I also tried format by hand and it solved most of the problem. 

It is ready for review.

2021-09-17 05:29 UTC, hugary1995 requested changes
Some minor naming questions and code suggestions.

2021-09-17 05:29 UTC, hugary1995 commented on include/auxkernels/ConditionalBoundsAux.h
> +class ConditionalBoundsAux;
I don't think we need a forward declaration here.

2021-09-17 05:29 UTC, hugary1995 commented on include/auxkernels/ConditionalBoundsAux.h
> +InputParameters validParams<ConditionalBoundsAux>();
This is the deprecated way of declaring `validParams`. Just remove it.

2021-09-17 05:29 UTC, hugary1995 commented on src/auxkernels/ConditionalBoundsAux.C
> +defineLegacyParams(ConditionalBoundsAux);
Remove this line.

2021-09-17 05:29 UTC, hugary1995 commented on src/auxkernels/ConditionalBoundsAux.C
> +      "variable to PETSc's SNES variational inequalities solver.");
```suggestion
      "This class conditionally enforces a bound. When the variable value is below a given threshold, a constant value is used as the bound; when the variable value is above a given threshold, irreversibility is enforced.");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/auxkernels/ConditionalBoundsAux.C
> +  return params;
You are also making a strong assumption in this class that this is imposing a lower bound. This is fine, but you need to suppress the corresponding parameter, for example
```
params.set<MooseEnum>("bound_type") = "lower";
params.suppressParameter<bool>("bound_type");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/auxkernels/ConditionalBoundsAux.C
> +  }
When there is only a single statement within the curly braces, you should remove the curly braces.
```suggestion
    return d_old;
  else
    return _fixed_bound_value;
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +                             "Ce()");
```suggestion
  params.addClassDescription("computes the external driving force for nucleation given a strength envelope. The implementation follows Kumar et. al. (2020).");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "energy_release_rate", "Gc", "energy release rate or fracture toughness");
I think we use `fracture_toughness` everywhere in RACCOON. So let's be consistent.
```suggestion
      "fracture_toughness", "Gc", "energy release rate or fracture toughness");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "phase_field_regularization_length", "l",
I think we use `regularization_length` everywhere in RACCOON.
```suggestion
      "regularization_length", "l",
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  params.addParam<MaterialPropertyName>("Lambda", "Lambda",
Should be lower case `lambda`.

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +                                "critical tensile strength");
```suggestion
                                "The tensile strength of the material beyond which the material fails.");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +                                "critical compressive strength");
```suggestion
                                "The compressive strength of the material beyond which the material fails.");
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  params.addRequiredParam<Real>("delta", "delta");
Please add an actually descriptive description for `delta`.

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  params.addParam<MaterialPropertyName>("rank_two_tensor", "stress",
Don't call it `rank_two_tensor`. I think it is better to call this parameter `stress`:
```suggestion
  params.addParam<MaterialPropertyName>("stress", "stress",
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "name of the material that holds the external_driving_force");
Let's try to be consistent with parameter naming. For example, we use the parameter `fracture_toughness` instead of `fracture_toughness_name` for the name of the fracture toughness. Similarly, I think we should name this parameter `external_driving_force` instead of `external_driving_force_name`.

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  ADReal _temp = _Gc[_qp] * 3.0 / _L[_qp] / 8.0;
No, I won't let you hard code this. The normalization constant `c0` isn't always `8/3`.

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +  ADReal I1 = _stress[_qp](0, 0) + _stress[_qp](1, 1) + _stress[_qp](2, 2);
```suggestion
  ADReal I1 = _stress[_qp].trace();
```

2021-09-17 05:29 UTC, hugary1995 commented on src/materials/GeneralizedExternalDrivingForce.C
> +              pow(_stress[_qp](2, 1), 2);
```suggestion
  ADRankTwoTensor stress_dev = _stress[_qp].deviatoric();
  ADReal J2 = stress_dev.doubleContraction(stress_dev);
```

2021-09-17 16:17 UTC, BoZeng1997 commented on src/materials/GeneralizedExternalDrivingForce.C
> +      "name of the material that holds the external_driving_force");
No, this is just the name of that parameter, not the parameter itself.

2021-09-20 07:31 UTC, hugary1995 commented
I just pushed three commits cleaning up everything. Take a look at the changes I made -- if you are fine with those then this PR is good to go.

I was mostly making minor style changes. But one mistake I noticed is that you named the test specification `test` instead of `tests`, and as a result the regression test wasn't being run. I've fixed that for you.

2021-09-20 07:34 UTC, hugary1995 commented
I would also like to thank you for your contribution! It is hard for everyone to make their first pull request. Hopefully you've learnt something from this PR. You should definitely be proud of this work!

2021-09-20 07:35 UTC, hugary1995 submitted a review, later dismissed

2021-09-20 07:36 UTC, hugary1995 commented
@milljm This is the PR waiting for CIVET tests.

2021-09-20 16:05 UTC, BoZeng1997 commented
Yeah, I think those modifications are great. Thank you for being **so patient** with this PR! I did learned a lot!

2021-09-20 16:07 UTC, hugary1995 approved these changes

2021-09-20 16:33 UTC, merged